FROM ubuntu:20.04

ARG USERNAME=admin
ARG PASSWORD=admin


RUN apt-get update && apt-get install -y openssh-server
RUN apt install sudo
RUN mkdir /var/run/sshd

RUN adduser --gecos "" --disabled-password ${USERNAME}
RUN echo "${USERNAME}:${PASSWORD}" | chpasswd
RUN usermod -aG sudo ${USERNAME}

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]