version: "3"
services:
  rundeck:
    image: jeremiasrg/rundeck:1.0.0
    container_name: rundeck
    volumes:
      - "./rundeck-config/framework.properties:/etc/rundeck/framework.properties:ro"
      - "./rundeck-config/project.properties:/etc/rundeck/project.properties:ro"
      - "./rundeck-config/rundeck-config.properties:/etc/rundeck/rundeck-config.properties:ro"
      - "./rundeck-config/resources.xml:/resources.xml:ro"
    ports:
      - 4440:4440
    networks:
      - myCompany

  ansible:
    image: jeremiasrg/ansible:1.0.0
    container_name: ansible
    volumes:
      - "./ansible-config/ansible.cfg:/etc/ansible/ansible.cfg:ro"
      - "./ansible-config/hosts:/etc/ansible/hosts:ro"
    networks:
      - myCompany

  dev01:
    image: jeremiasrg/ubuntu-ssh:1.0.0
    container_name: dev01
    networks:
      - myCompany

  dev02:
    image: jeremiasrg/ubuntu-ssh:1.0.0
    container_name: dev02
    networks:
      - myCompany

networks:
  myCompany:
    driver: bridge
