version: "3"
services:
  rundeck-ansible:
    image: jeremiasrg/rundeck-ansible:1.0.1
    container_name: rundeck-ansible
    volumes:
      - "./rundeck-config/framework.properties:/etc/rundeck/framework.properties:ro"
      - "./rundeck-config/project.properties:/etc/rundeck/project.properties:ro"
      - "./rundeck-config/rundeck-config.properties:/etc/rundeck/rundeck-config.properties:ro"

      
      - "./ansible/ansible-config/ansible.cfg:/etc/ansible/ansible.cfg:ro"
      - "./ansible/ansible-config/hosts:/etc/ansible/hosts:ro"
      - "./ansible/playbooks:/home/ansible/playbooks:ro"

    ports:
      - 4440:4440
    networks:
      - myCompanyNetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      discovery.type: single-node
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: elastic
    networks:
      - myCompanyNetwork

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - myCompanyNetwork

  dev01:
    image: jeremiasrg/ubuntu-ssh:1.0.0
    container_name: dev01
    networks:
      - myCompanyNetwork

  dev02:
    image: jeremiasrg/ubuntu-ssh:1.0.0
    container_name: dev02
    networks:
      - myCompanyNetwork

networks:
  myCompanyNetwork:
    driver: bridge
